name: Deploy al servidor

on: push

jobs:
  primer_job:
    runs-on: ubuntu-latest

    steps:
      - name: Generar archivo
        run: |
          echo "Archivo prueba, hola" >> test.log

      - name: Subir archivo
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: test.log
