name: Deploy al servidor

on: push

jobs:
  primer_job:
    runs-on: ubuntu-latest

    steps:
      - name: Generar archivo
        run: |
          echo "Archivo prueba, hola" >> test.log

      - name: Subir archivo
        uses: actions/upload-artifact@v4
        with:
          name: archivo-test
          path: test.log

  segundo_job:
    runs-on: ubuntu-latest
    needs: primer_job

    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: archivo-test

      - name: Mostrar contenido del archivo
        run:  cat test.log