name: Deploy al servidor

on: push

jobs:
  primer_job:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        message: [ "Hola", "Cody", "Bootcamp GitHub Actions" ]

    steps:
      - name: Imprimir mensaje
        run: echo "${{ matrix.message }}"